apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: dev

spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 071680046254.dkr.ecr.us-east-1.amazonaws.com/order-service:158b598c2540e5116276a70117ad9ae99c9dcf4b
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
            readinessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 15
              periodSeconds: 20



